# Generated by Django 4.1.2 on 2022-10-14 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_enfermero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfermero',
            name='area',
            field=models.CharField(max_length=30, verbose_name='area'),
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parentesco', models.CharField(max_length=30, verbose_name='parentesco')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familiar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
