# Generated by Django 4.1.2 on 2022-10-15 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0004_historiaclinica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enfermero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfermero_std', to=settings.AUTH_USER_MODEL)),
                ('familiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familiar_std', to=settings.AUTH_USER_MODEL)),
                ('historiaClinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiaClinica_std', to='authApp.historiaclinica')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medico_std', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
